name: docker

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  test:
    uses: ./.github/workflows/unit-testing.yml
  test-resolve:
    uses: ./.github/workflows/test-resolve.yml
  image-build:
    name: Build Image(s)
    needs: [test-resolve]
    runs-on: ubuntu-latest
    steps:
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::876451484466:role/e3x/github-actions/e3x-github-actions-default
          aws-region: us-west-2

      - id: login-ecr
        name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          file: docker/Dockerfile
          platforms: linux/amd64 #,linux/arm64
          push: true
          tags: "${{ steps.login-ecr.outputs.registry }}/e3/nmt:main"
