name: pre-commit

on:
  pull_request:
    branches:
      - main
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: --from-ref origin/main --to-ref HEAD
  if_error_or_failure:
    runs-on: ubuntu-latest
    if: >-
      github.event.state == 'error' ||
      github.event.state == 'failure'
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            if core.setFailed("Pre-commit failed. Please run `pre-commit run --show-diff-on-failure --color=always --from-ref origin/main --to-ref HEAD`")
