name: Run Resolve Test Case

on:
  workflow_call:
  pull_request:
    branches:
      - main
    paths:
      - 'new_modeling_toolkit/**'
      - 'pyproject.toml'
      - '.github/workflows/**'

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    container: continuumio/miniconda3
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create NMT environment (Miniconda)
        run: |
          conda env create -f environment-ci.yml

      - name: Run pytest
        run: |
          conda run -n kit-ci --no-capture-output --cwd tests/resolve/ pytest test_run_opt.py
