exclude: "RECAP-2.0/.*|notebooks/resolve-runner.py" # Need to skip because doing some funky things with inline CLI commands
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: [ --maxkb=20000 ]
      - id: check-ast
      - id: check-merge-conflict
      - id: debug-statements
      - id: trailing-whitespace
        exclude: docs/

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: [
            --skip, B101
        ]
        exclude: new_modeling_toolkit/cli/__init__.py

  - repo: https://github.com/akaihola/darker
    rev: v2.0.0
    hooks:
      - id: darker
        exclude: new_modeling_toolkit/resolve/model_formulation.py|new_modeling_toolkit/resolve/extras/.*

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout

  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [
            --in-place,
            --recursive,
            --remove-all-unused-imports,
            --ignore-init-module-imports,
        ]

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
