name: kit

channels:
  - conda-forge
  - gurobi

dependencies:
  - python>=3.11,<3.12
  - gurobi>=11.0,<12.0

  # Jupyter
  - ipywidgets=8.1.3
  - bokeh>=3.1,<4.0
  - hera>=5.13,<6.0
  - ipywidgets=8.1.3
  - jupyterlab-git=0.50.1
  - jupytext=1.16.1
  - panel>=1.5,<2.0

  # DVC
  - dvc>=3.63
  - dvc-s3>=3.2
  - libsqlite<3.49.0

  - aiobotocore=2.24.1
  - boto3=1.39.11
  - botocore=1.39.11
  - s3fs=2024.12.0   # keeps fsspec recent enough for dvc-s3

  - pip:
      - -e .
