name: base

channels:
  - conda-forge
  - gurobi

dependencies:
  - python>=3.11,<3.12
  - gurobi>=11.0,<12.0

  # Jupyter
  - bokeh>=3.1.0
  - hera=5.13.1
  - ipywidgets=8.1.3
  - jupyterlab-git=0.50.1
  - jupytext=1.16.1
  - panel=1.5.2

  # DVC
  - dvc>=3.55
  - dvc-s3>=3.2
  - libsqlite<3.49.0

  - pip:
      - -r requirements.txt
