name: kit-ci

channels:
  - conda-forge
  - gurobi

dependencies:
  - gurobi=11.0.0
  - pip=22.3.1
  - python>=3.10,<3.12
  - setuptools=66.1.1

  - pip:
      # Install current repo as editable package
      - -e ".[dev]"
