apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-workflows
spec:
  chart:
    spec:
      chart: argo-workflows
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: argo-charts
      version: 0.33.1
  interval: 60s
  values:
    crds:
      install: false

    createAggregateRoles: false

    controller:
      clusterWorkflowTemplates:
        enabled: false
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: ${ARGO_WORKFLOW_ROLE_ARN}

    server:
      clusterWorkflowTemplates:
        enabled: false
        enableEditing: false
      extraArgs:
        - '--auth-mode=server'
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: ${ARGO_WORKFLOW_ROLE_ARN}

    singleNamespace: true
    useStaticCredentials: false

    workflow:
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: ${ARGO_WORKFLOW_ROLE_ARN}
        create: true
